/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#5e5e5e',
        'surface-container-high': '#e5e8ed',
        'tertiary-fixed-dim': '#e3bccd',
        'surface-container-low': '#f1f4f9',
        'primary-fixed-dim': '#c6c6c6',
        'on-surface-variant': '#45474a',
        'on-secondary': '#ffffff',
        'on-primary-container': '#727272',
        'tertiary-container': '#fff8f8',
        'on-primary': '#ffffff',
        background: '#f7f9fe',
        surface: '#f7f9fe',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#c4c4e2',
        'secondary-container': '#e0e0ff',
        tertiary: '#755565',
        'on-secondary-container': '#61627c',
        'inverse-surface': '#2d3135',
        'inverse-primary': '#c6c6c6',
        'on-primary-fixed': '#1b1b1b',
        'surface-dim': '#d7dadf',
        'on-error-container': '#93000a',
        'primary-fixed': '#e2e2e2',
        'surface-container': '#ebeef3',
        'surface-variant': '#dfe3e8',
        primary: '#5e5e5e',
        'on-secondary-fixed-variant': '#43455e',
        outline: '#76777b',
        'on-secondary-fixed': '#181a30',
        'on-tertiary-fixed-variant': '#5b3e4d',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#474747',
        'on-background': '#181c20',
        error: '#ba1a1a',
        secondary: '#5b5c76',
        'inverse-on-surface': '#eef1f6',
        'on-tertiary-container': '#8a6979',
        'primary-container': '#f9f9f9',
        'on-tertiary-fixed': '#2b1421',
        'on-surface': '#181c20',
        'secondary-fixed': '#e0e0ff',
        'outline-variant': '#c6c6cb',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#dfe3e8',
        'surface-bright': '#f7f9fe',
        'tertiary-fixed': '#ffd8e9',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
